"""Entry-state forensics for Krypton research only.

For each historical trade generated by the frozen BTC>SMA200 baseline, this
script reconstructs features known at the signal close immediately BEFORE the
next-open entry. It then compares winners vs losers and 2025 H1 stops vs stops
from other periods.

This is diagnosis, not a classifier or parameter search. No feature is used to
change trades in this script and no holdout is opened.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone

import numpy as np
import pandas as pd

import cross_asset_diagnostics as cad
import forensic_diagnostics as fd
import regime_diagnostics as rd
import walk_forward as wf
from config import TRADING_PAIRS

FOCUS_START = pd.Timestamp("2025-01-07", tz="UTC")
FOCUS_END = pd.Timestamp("2025-07-05", tz="UTC")


def _latest_loc(df: pd.DataFrame, ts) -> int | None:
    eligible = df.index[df.index <= pd.Timestamp(ts)]
    if len(eligible) == 0:
        return None
    return int(df.index.get_loc(eligible[-1]))


def _return_at(close: pd.Series, loc: int, bars: int) -> float:
    if loc < bars or bars <= 0:
        return np.nan
    prev = float(close.iloc[loc - bars])
    cur = float(close.iloc[loc])
    return cur / prev - 1.0 if prev > 0 else np.nan


def _window_efficiency(close: pd.Series, loc: int, bars: int) -> float:
    start = max(0, loc - bars)
    return cad._trend_efficiency(close.iloc[start : loc + 1])


def _window_vol(close: pd.Series, loc: int, bars: int) -> float:
    start = max(0, loc - bars)
    r = close.iloc[start : loc + 1].pct_change().dropna()
    return float(r.std() * np.sqrt(365.0)) if len(r) > 1 else np.nan


def _crossings(close: pd.Series, sma: pd.Series, loc: int, bars: int) -> float:
    start = max(0, loc - bars)
    c = close.iloc[start : loc + 1]
    s = sma.iloc[start : loc + 1]
    valid = s.notna()
    if valid.sum() < 2:
        return np.nan
    above = (c[valid] > s[valid]).astype(int)
    return float((above.diff().abs() == 1).sum())


def _drawdown_from_high(close: pd.Series, loc: int, bars: int) -> float:
    start = max(0, loc - bars + 1)
    window = close.iloc[start : loc + 1].dropna().astype(float)
    if window.empty:
        return np.nan
    high = float(window.max())
    return float(window.iloc[-1] / high - 1.0) if high > 0 else np.nan


def _long_signal_age(signals: pd.Series, loc: int) -> float:
    aligned = signals.iloc[: loc + 1]
    if aligned.empty or int(aligned.iloc[-1]) != 1:
        return 0.0
    age = 0
    for value in reversed(aligned.tolist()):
        if int(value) != 1:
            break
        age += 1
    return float(age)


def _state_for_asset(data, symbol: str, ts) -> dict:
    item = data[symbol]
    df = item["df"]
    loc = _latest_loc(df, ts)
    if loc is None:
        return {}
    signal_ts = df.index[loc]
    close = df["close"].astype(float)
    sma = item["sma200"].reindex(df.index)
    px = float(close.iloc[loc])
    sma_val = float(sma.iloc[loc]) if pd.notna(sma.iloc[loc]) else np.nan
    atr = item["atr"].reindex(df.index)
    atr_val = float(atr.iloc[loc]) if pd.notna(atr.iloc[loc]) else np.nan
    signals = item["signals"].reindex(df.index)
    return {
        "signal_time": signal_ts,
        "close": px,
        "above_sma200": float(px > sma_val) if np.isfinite(sma_val) else np.nan,
        "sma200_distance": px / sma_val - 1.0 if np.isfinite(sma_val) and sma_val > 0 else np.nan,
        "mom20": _return_at(close, loc, 20),
        "mom30": _return_at(close, loc, 30),
        "mom60": _return_at(close, loc, 60),
        "mom90": _return_at(close, loc, 90),
        "trend_eff30": _window_efficiency(close, loc, 30),
        "trend_eff60": _window_efficiency(close, loc, 60),
        "realized_vol30": _window_vol(close, loc, 30),
        "realized_vol60": _window_vol(close, loc, 60),
        "sma_crossings30": _crossings(close, sma, loc, 30),
        "sma_crossings60": _crossings(close, sma, loc, 60),
        "drawdown_from_high20": _drawdown_from_high(close, loc, 20),
        "drawdown_from_high60": _drawdown_from_high(close, loc, 60),
        "long_signal_age": _long_signal_age(signals, loc),
        "atr_pct": atr_val / px if np.isfinite(atr_val) and px > 0 else np.nan,
    }


def entry_features(data, symbols, symbol, entry_time) -> dict:
    df = data[symbol]["df"]
    entry_loc = _latest_loc(df, entry_time)
    if entry_loc is None or entry_loc == 0:
        return {}
    signal_ts = df.index[entry_loc - 1]

    asset = _state_for_asset(data, symbol, signal_ts)
    btc = _state_for_asset(data, "BTCUSDT", signal_ts)
    states = {s: _state_for_asset(data, s, signal_ts) for s in symbols}

    above = [v.get("above_sma200", np.nan) for v in states.values()]
    breadth = float(np.nanmean(above)) if np.isfinite(above).any() else np.nan
    out = {
        "signal_time": signal_ts,
        "cross_asset_sma_breadth": breadth,
        "cross_asset_confirm_2of3": float(breadth >= (2.0 / 3.0)) if np.isfinite(breadth) else np.nan,
        "btc_on_weak_breadth": (
            float(btc.get("above_sma200", np.nan) > 0.5 and breadth < (2.0 / 3.0))
            if np.isfinite(btc.get("above_sma200", np.nan)) and np.isfinite(breadth) else np.nan
        ),
    }
    for lookback in (30, 60, 90):
        vals = [v.get(f"mom{lookback}", np.nan) for v in states.values()]
        valid = [x for x in vals if np.isfinite(x)]
        out[f"momentum{lookback}_breadth"] = float(np.mean([x > 0 for x in valid])) if valid else np.nan
    if np.isfinite(out["momentum30_breadth"]) and np.isfinite(out["momentum90_breadth"]):
        out["momentum30_minus_90_breadth"] = out["momentum30_breadth"] - out["momentum90_breadth"]
    else:
        out["momentum30_minus_90_breadth"] = np.nan

    for prefix, state in (("asset", asset), ("btc", btc)):
        for key in (
            "above_sma200", "sma200_distance", "mom20", "mom30", "mom60", "mom90",
            "trend_eff30", "trend_eff60", "realized_vol30", "realized_vol60",
            "sma_crossings30", "sma_crossings60", "drawdown_from_high20",
            "drawdown_from_high60", "long_signal_age", "atr_pct",
        ):
            out[f"{prefix}_{key}"] = state.get(key, np.nan)
    if np.isfinite(out.get("asset_mom60", np.nan)) and np.isfinite(out.get("btc_mom60", np.nan)):
        out["asset_relative_mom60"] = out["asset_mom60"] - out["btc_mom60"]
    else:
        out["asset_relative_mom60"] = np.nan
    for prefix in ("asset", "btc"):
        mom20 = out.get(f"{prefix}_mom20", np.nan)
        mom90 = out.get(f"{prefix}_mom90", np.nan)
        out[f"{prefix}_mom20_minus_mom90"] = (
            mom20 - mom90 if np.isfinite(mom20) and np.isfinite(mom90) else np.nan
        )
    return out


def add_trade_history_features(trades: pd.DataFrame) -> pd.DataFrame:
    """Attach only same-symbol trade history known by each signal close."""
    if trades.empty:
        return trades.copy()
    out = trades.copy()
    out["entry_time"] = pd.to_datetime(out["entry_time"], utc=True)
    out["exit_time"] = pd.to_datetime(out["exit_time"], utc=True)
    out["signal_time"] = pd.to_datetime(out["signal_time"], utc=True)
    feature_rows = {}
    for _, group in out.sort_values(["symbol", "entry_time", "exit_time"]).groupby("symbol", sort=False):
        history = []
        for idx, trade in group.iterrows():
            signal_time = trade["signal_time"]
            known = [h for h in history if h["exit_time"] <= signal_time]
            prior = known[-1] if known else None
            prior_stops = [h for h in known if str(h["reason"]).startswith("SL")]
            consecutive_stops = 0
            for event in reversed(known):
                if str(event["reason"]).startswith("SL"):
                    consecutive_stops += 1
                else:
                    break
            days_since_exit = (
                float((signal_time - prior["exit_time"]).days) if prior is not None else np.nan
            )
            days_since_stop = (
                float((signal_time - prior_stops[-1]["exit_time"]).days) if prior_stops else np.nan
            )
            feature_rows[idx] = {
                "prior_exit_was_stop": float(str(prior["reason"]).startswith("SL")) if prior else 0.0,
                "days_since_prior_exit": days_since_exit,
                "days_since_prior_stop": days_since_stop,
                "immediate_reentry_after_stop": float(
                    prior is not None
                    and str(prior["reason"]).startswith("SL")
                    and days_since_exit == 0.0
                ),
                "stops_last_30d": float(sum(
                    h["exit_time"] >= signal_time - pd.Timedelta(days=30) for h in prior_stops
                )),
                "stops_last_60d": float(sum(
                    h["exit_time"] >= signal_time - pd.Timedelta(days=60) for h in prior_stops
                )),
                "consecutive_prior_stops": float(consecutive_stops),
            }
            history.append({"exit_time": trade["exit_time"], "reason": trade["reason"]})
    history_features = pd.DataFrame.from_dict(feature_rows, orient="index")
    for column in history_features:
        out[column] = history_features[column].reindex(out.index)
    return out


def build_trade_frame(data, symbols, start, end, window_days=180):
    rows = []
    for period, ps, pe in rd._periods(start, end, window_days):
        result = fd.simulate_forensic(data, symbols, ps, pe, regime_mode="btc")
        trades = result["trades"]
        if trades.empty:
            continue
        old_regime = rd.classify_period(rd._btc_period_return(data, ps, pe))
        for _, trade in trades.iterrows():
            features = entry_features(data, symbols, str(trade["symbol"]), trade["entry_time"])
            actual_risk = float(trade.get("actual_risk", np.nan))
            pnl = float(trade["pnl"])
            reason = str(trade["reason"])
            if reason.startswith("TP"):
                exit_class = "TP"
            elif reason.startswith("SL"):
                exit_class = "SL"
            else:
                exit_class = "OTHER"
            row = {
                "period": period,
                "period_start": ps.date().isoformat(),
                "period_end": pe.date().isoformat(),
                "old_btc_regime": old_regime,
                "symbol": trade["symbol"],
                "entry_time": trade["entry_time"],
                "exit_time": trade["exit_time"],
                "reason": reason,
                "exit_class": exit_class,
                "pnl": pnl,
                "R": pnl / actual_risk if np.isfinite(actual_risk) and actual_risk > 0 else np.nan,
                "winner": int(pnl > 0),
                "is_stop": int(str(trade["reason"]).startswith("SL")),
                "entry_weight": trade.get("entry_weight", np.nan),
                "holding_days": trade.get("holding_days", np.nan),
                "post_exit_return_5d": trade.get("post_exit_return_5d", np.nan),
                "post_exit_return_20d": trade.get("post_exit_return_20d", np.nan),
                "focus_2025_h1": int(FOCUS_START <= pd.Timestamp(trade["entry_time"]) <= FOCUS_END),
                **features,
            }
            rows.append(row)
    return add_trade_history_features(pd.DataFrame(rows))


FEATURES = [
    "cross_asset_sma_breadth", "cross_asset_confirm_2of3", "btc_on_weak_breadth",
    "momentum30_breadth", "momentum60_breadth", "momentum90_breadth",
    "btc_sma200_distance", "btc_mom20", "btc_mom60", "btc_mom90",
    "btc_mom20_minus_mom90", "momentum30_minus_90_breadth",
    "btc_trend_eff30", "btc_trend_eff60", "btc_realized_vol30", "btc_realized_vol60",
    "btc_sma_crossings30", "btc_sma_crossings60", "btc_drawdown_from_high20",
    "btc_drawdown_from_high60", "btc_long_signal_age",
    "asset_above_sma200", "asset_sma200_distance", "asset_mom20", "asset_mom60", "asset_mom90",
    "asset_mom20_minus_mom90", "asset_relative_mom60", "asset_trend_eff30", "asset_trend_eff60",
    "asset_realized_vol30", "asset_realized_vol60", "asset_sma_crossings30",
    "asset_sma_crossings60", "asset_drawdown_from_high20", "asset_drawdown_from_high60",
    "asset_long_signal_age", "asset_atr_pct", "entry_weight",
    "prior_exit_was_stop", "days_since_prior_exit", "days_since_prior_stop",
    "immediate_reentry_after_stop", "stops_last_30d", "stops_last_60d",
    "consecutive_prior_stops",
]


def _feature_comparison(frame: pd.DataFrame, scope: str) -> pd.DataFrame:
    rows = []
    if frame.empty:
        return pd.DataFrame()
    for feature in FEATURES:
        if feature not in frame:
            continue
        vals = pd.to_numeric(frame[feature], errors="coerce")
        win = vals[frame["winner"] == 1].dropna()
        loss = vals[frame["winner"] == 0].dropna()
        r = pd.to_numeric(frame["R"], errors="coerce")
        corr_frame = pd.DataFrame({"x": vals, "R": r}).dropna()
        # pandas delegates method="spearman" to scipy, which is intentionally
        # not a Krypton runtime dependency. Pearson correlation of average
        # ranks is the same Spearman coefficient and keeps this diagnostic
        # runnable in the project's pinned CI environment.
        spearman = (
            float(corr_frame["x"].rank().corr(corr_frame["R"].rank()))
            if len(corr_frame) >= 3 else np.nan
        )
        rows.append({
            "scope": scope,
            "feature": feature,
            "n": int(vals.notna().sum()),
            "winner_median": float(win.median()) if len(win) else np.nan,
            "loser_median": float(loss.median()) if len(loss) else np.nan,
            "winner_minus_loser": float(win.median() - loss.median()) if len(win) and len(loss) else np.nan,
            "spearman_with_R": spearman,
        })
    return pd.DataFrame(rows)


def tp_sl_comparison(frame: pd.DataFrame, scope: str) -> pd.DataFrame:
    """Compare only fixed-barrier outcomes; signal/EOD exits stay separate."""
    if frame.empty or "exit_class" not in frame:
        return pd.DataFrame()
    core = frame[frame["exit_class"].isin(["TP", "SL"])]
    rows = []
    for feature in FEATURES:
        if feature not in core:
            continue
        vals = pd.to_numeric(core[feature], errors="coerce")
        tp = vals[core["exit_class"] == "TP"].dropna()
        sl = vals[core["exit_class"] == "SL"].dropna()
        rows.append({
            "scope": scope,
            "feature": feature,
            "tp_n": int(len(tp)),
            "sl_n": int(len(sl)),
            "tp_median": float(tp.median()) if len(tp) else np.nan,
            "sl_median": float(sl.median()) if len(sl) else np.nan,
            "tp_minus_sl": float(tp.median() - sl.median()) if len(tp) and len(sl) else np.nan,
        })
    return pd.DataFrame(rows)


def focus_monthly_outcomes(trades: pd.DataFrame) -> pd.DataFrame:
    focus = trades[trades["focus_2025_h1"] == 1].copy()
    if focus.empty:
        return pd.DataFrame()
    focus["month"] = pd.to_datetime(focus["entry_time"], utc=True).dt.strftime("%Y-%m")
    rows = []
    for month, group in focus.groupby("month", sort=True):
        rows.append({
            "month": month,
            "trades": int(len(group)),
            "wins": int(group["winner"].sum()),
            "stops": int((group["exit_class"] == "SL").sum()),
            "take_profits": int((group["exit_class"] == "TP").sum()),
            "other_exits": int((group["exit_class"] == "OTHER").sum()),
            "total_R": float(group["R"].sum()),
            "pnl": float(group["pnl"].sum()),
            "weak_breadth_entries": int((group["btc_on_weak_breadth"] == 1).sum()),
            "median_momentum30_breadth": float(group["momentum30_breadth"].median()),
            "median_momentum60_breadth": float(group["momentum60_breadth"].median()),
        })
    return pd.DataFrame(rows)


def period_outcomes(trades: pd.DataFrame) -> pd.DataFrame:
    """Show whether an apparent entry-state separator is stable across cycles."""
    if trades.empty:
        return pd.DataFrame()
    rows = []
    for (period, start, end), group in trades.groupby(
        ["period", "period_start", "period_end"], sort=True
    ):
        rows.append({
            "period": int(period),
            "period_start": start,
            "period_end": end,
            "trades": int(len(group)),
            "win_rate": float(group["winner"].mean()),
            "stops": int(group["is_stop"].sum()),
            "total_R": float(group["R"].sum()),
            "pnl": float(group["pnl"].sum()),
            "median_asset_long_signal_age": float(group["asset_long_signal_age"].median()),
            "median_btc_long_signal_age": float(group["btc_long_signal_age"].median()),
            "median_momentum30_breadth": float(group["momentum30_breadth"].median()),
            "median_momentum60_breadth": float(group["momentum60_breadth"].median()),
            "median_momentum90_breadth": float(group["momentum90_breadth"].median()),
            "median_asset_mom60": float(group["asset_mom60"].median()),
            "median_btc_mom60": float(group["btc_mom60"].median()),
            "weak_breadth_entries": int((group["btc_on_weak_breadth"] == 1).sum()),
            "immediate_reentries_after_stop": int((group["immediate_reentry_after_stop"] == 1).sum()),
        })
    return pd.DataFrame(rows)


def _group_outcomes(trades: pd.DataFrame) -> pd.DataFrame:
    rows = []
    grouped_features = (
        "btc_on_weak_breadth", "cross_asset_confirm_2of3", "asset_above_sma200",
        "immediate_reentry_after_stop", "prior_exit_was_stop",
    )
    for feature in grouped_features:
        if feature not in trades:
            continue
        for value, g in trades.dropna(subset=[feature]).groupby(feature):
            rows.append({
                "scope": "all",
                "group_feature": feature,
                "group_value": float(value),
                "trades": len(g),
                "win_rate": float(g["winner"].mean()),
                "mean_R": float(g["R"].mean()),
                "median_R": float(g["R"].median()),
                "total_R": float(g["R"].sum()),
            })
    focus = trades[trades["focus_2025_h1"] == 1]
    for feature in grouped_features:
        if feature not in focus:
            continue
        for value, g in focus.dropna(subset=[feature]).groupby(feature):
            rows.append({
                "scope": "2025_h1",
                "group_feature": feature,
                "group_value": float(value),
                "trades": len(g),
                "win_rate": float(g["winner"].mean()),
                "mean_R": float(g["R"].mean()),
                "median_R": float(g["R"].median()),
                "total_R": float(g["R"].sum()),
            })
    return pd.DataFrame(rows)


def stop_comparison(trades: pd.DataFrame) -> pd.DataFrame:
    stops = trades[trades["is_stop"] == 1]
    h1 = stops[stops["focus_2025_h1"] == 1]
    other = stops[stops["focus_2025_h1"] == 0]
    rows = []
    for feature in FEATURES:
        if feature not in stops:
            continue
        a = pd.to_numeric(h1[feature], errors="coerce").dropna()
        b = pd.to_numeric(other[feature], errors="coerce").dropna()
        rows.append({
            "feature": feature,
            "h1_stop_n": len(a),
            "other_stop_n": len(b),
            "h1_stop_median": float(a.median()) if len(a) else np.nan,
            "other_stop_median": float(b.median()) if len(b) else np.nan,
            "h1_minus_other_stop": float(a.median() - b.median()) if len(a) and len(b) else np.nan,
        })
    return pd.DataFrame(rows)


def main():
    p = argparse.ArgumentParser(description="Krypton entry-state forensic diagnostics")
    p.add_argument("--start", default="2020-08-01")
    p.add_argument("--end", default="2026-06-30")
    p.add_argument("--window-days", type=int, default=180)
    args = p.parse_args()

    start = datetime.strptime(args.start, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    end = datetime.strptime(args.end, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    symbols = list(TRADING_PAIRS)
    data = wf._prepare_data(symbols, start, end)
    trades = build_trade_frame(data, symbols, start, end, args.window_days)

    comparisons = []
    comparisons.append(_feature_comparison(trades, "all"))
    comparisons.append(_feature_comparison(trades[trades["focus_2025_h1"] == 1], "2025_h1"))
    comparisons.append(_feature_comparison(trades[trades["focus_2025_h1"] == 0], "outside_2025_h1"))
    feature_summary = pd.concat(comparisons, ignore_index=True)
    groups = _group_outcomes(trades)
    stops = stop_comparison(trades)
    tp_sl = pd.concat([
        tp_sl_comparison(trades, "all"),
        tp_sl_comparison(trades[trades["focus_2025_h1"] == 1], "2025_h1"),
        tp_sl_comparison(trades[trades["focus_2025_h1"] == 0], "outside_2025_h1"),
    ], ignore_index=True)
    monthly = focus_monthly_outcomes(trades)
    periods = period_outcomes(trades)

    trades.to_csv("entry_state_trades.csv", index=False)
    feature_summary.to_csv("entry_state_feature_summary.csv", index=False)
    groups.to_csv("entry_state_groups.csv", index=False)
    stops.to_csv("entry_state_stop_comparison.csv", index=False)
    tp_sl.to_csv("entry_state_tp_sl_summary.csv", index=False)
    monthly.to_csv("entry_state_focus_monthly.csv", index=False)
    periods.to_csv("entry_state_period_summary.csv", index=False)

    focus = trades[trades["focus_2025_h1"] == 1]
    report = {
        "trades_total": int(len(trades)),
        "signal_not_before_entry_violations": int(
            (pd.to_datetime(trades["signal_time"], utc=True) >= pd.to_datetime(trades["entry_time"], utc=True)).sum()
        ),
        "focus_2025_h1": {
            "trades": int(len(focus)),
            "win_rate": float(focus["winner"].mean()) if len(focus) else None,
            "mean_R": float(focus["R"].mean()) if len(focus) else None,
            "stops": int(focus["is_stop"].sum()) if len(focus) else 0,
            "btc_on_weak_breadth_trades": int((focus["btc_on_weak_breadth"] == 1).sum()) if len(focus) else 0,
        },
    }
    with open("entry_state_report.json", "w", encoding="utf-8") as fh:
        json.dump(report, fh, indent=2, ensure_ascii=False)

    print("\nENTRY GROUP OUTCOMES")
    print(groups.to_string(index=False))
    print("\n2025 H1 STOP DIFFERENCES (largest absolute median differences)")
    if not stops.empty:
        shown = stops.assign(abs_diff=stops["h1_minus_other_stop"].abs()).sort_values("abs_diff", ascending=False).head(15)
        print(shown.drop(columns="abs_diff").to_string(index=False))
    print("\n2025 H1 TP VS SL ENTRY-STATE DIFFERENCES")
    focus_tp_sl = tp_sl[tp_sl["scope"] == "2025_h1"]
    if not focus_tp_sl.empty:
        shown = focus_tp_sl.assign(abs_diff=focus_tp_sl["tp_minus_sl"].abs()).sort_values("abs_diff", ascending=False).head(15)
        print(shown.drop(columns="abs_diff").to_string(index=False))
    print("\n2025 H1 MONTHLY OUTCOMES")
    if not monthly.empty:
        print(monthly.to_string(index=False))
    print("\nPERIOD ENTRY-STATE OUTCOMES")
    if not periods.empty:
        print(periods.to_string(index=False))
    print("\nFEATURES MOST ASSOCIATED WITH R (all trades, absolute Spearman)")
    all_scope = feature_summary[feature_summary["scope"] == "all"].copy()
    if not all_scope.empty:
        shown = all_scope.assign(abs_corr=all_scope["spearman_with_R"].abs()).sort_values("abs_corr", ascending=False).head(15)
        print(shown.drop(columns="abs_corr").to_string(index=False))
    print("\n" + json.dumps(report, indent=2, ensure_ascii=False))
    print("Arquivos: entry_state_trades.csv | entry_state_feature_summary.csv | entry_state_groups.csv | entry_state_stop_comparison.csv | entry_state_tp_sl_summary.csv | entry_state_focus_monthly.csv | entry_state_period_summary.csv | entry_state_report.json")


if __name__ == "__main__":
    main()
